USE DATAWAREHOUSE;

-- QUALITY CHECK -> A PRIMARY KEY MUST BE UNIQUE AND NOT NULL

-- CHECK FOR NULLS AND DUPLICATES IN PRIMARY KEY
-- EXPECTATION : NO RESULT

SELECT 
CST_ID,
COUNT(*)
FROM BRONZE.crm_cust_info
GROUP BY cst_id
HAVING COUNT(*) > 1 OR cst_id IS NULL


-- SECOND CHECK FOR UNWANTED SPACES IN STRING VALUES 
-- LOGIC => IF THE OG VALUES IS NOT EQUAL TO THE SAME VALUE AFTER TRIMMING IT MEANS THERE ARE SPACES !
-- TRIM() =>  REMOVE LEADING AND TRAILING SPACES FROM A STRING


SELECT 
cst_firstname
FROM BRONZE.crm_cust_info
WHERE cst_firstname != TRIM(CST_FIRSTNAME);


-- THIRD CHECK FOR THE CONSISTENCY OF VALUES IN LOW CARDINALITY COLUMNS
-- DATA STANDARDIZATION & CONSISTENCY

SELECT DISTINCT CST_GNDR FROM bronze.crm_cust_info;
SELECT DISTINCT cst_marital_status FROM bronze.crm_cust_info;