-- FIRST REMOVE DUPLICATES PRIMARY KEYS

-- SECOND CHECK FOR UNWANTED SPACES IN STRING VALUES 
   -- LOGIC => IF THE OG VALUES IS NOT EQUAL TO THE SAME VALUE AFTER TRIMMING IT MEANS THERE ARE SPACES !
   -- TRIM() =>  REMOVE LEADING AND TRAILING SPACES FROM A STRING

-- THIRD CHECK FOR THE CONSISTENCY OF VALUES IN LOW CARDINALITY COLUMNS
   -- IN OUR DATA WAREHOUSE, WE AIM TO STORE CLEAR AND MEANINGFUL VALUES RATHER THAN USING ABBREVIATED TERMS.
   -- IN OUR DATA WAREHOUSE, WE USE THE DEFAULT VALUE 'N/A' FOR MISSING VALUES.
   -- APPLY UPPER() JUST IN CASE MIXED-CASE VALUES APPEAR LATER IN YOUR COLUMN.



INSERT INTO silver.crm_cust_info(
   cst_id,
   cst_key,
   cst_firstname,
   cst_lastname,
   cst_marital_status,
   cst_gndr,
   cst_create_date
)

SELECT 
cst_id,
cst_key,
TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME, -- REMOVE LEADING AND TRAILING SPACES FROM A STRING
TRIM(CST_LASTNAME) AS CST_LASTNAME,   -- REMOVE LEADING AND TRAILING SPACES FROM A STRING

CASE WHEN UPPER(TRIM(cst_marital_status)) = 'S' THEN 'Single'
     WHEN UPPER(TRIM(cst_marital_status)) = 'M' THEN 'Married'
     ELSE 'N/A'
END cst_marital_status, -- NORMALIZE MARITAL  STATUS VALUES TO READABLE FORMAT

CASE WHEN UPPER(TRIM(cst_gndr)) = 'F' THEN 'Female'
     WHEN UPPER(TRIM(cst_gndr)) = 'M' THEN 'Male'
     ELSE 'N/A'
END cst_gndr, -- NORMALIZE GENDER VALUES TO READABLE FORMAT
cst_create_date
FROM (
SELECT *,
ROW_NUMBER() OVER (PARTITION BY CST_ID ORDER BY CST_CREATE_DATE DESC) AS FLAG_LAST
FROM bronze.crm_cust_info
where cst_id IS NOT NULL
) T WHERE FLAG_LAST = 1; -- SELECT THE MOST RECENT RECORD PER CUSTOMER



SELECT * FROM silver.crm_cust_info;