USE DATAWAREHOUSE;

-- QUALITY CHECK -> A PRIMARY KEY MUST BE UNIQUE AND NOT NULL

-- CHECK FOR NULLS AND DUPLICATES IN PRIMARY KEY
-- EXPECTATION : NO RESULT

SELECT 
prd_ID,
COUNT(*)
FROM BRONZE.crm_prd_info
GROUP BY prd_id
HAVING COUNT(*) > 1 OR prd_id IS NULL;

-- CHEAK NULL AND REPLACE NULL

SELECT PRD_COST
FROM BRONZE.CRM_PRD_INFO
WHERE PRD_COST < 0 AND PRD_COST IS NULL;


-- DATA STANDARIZATION & CONSISTECY
SELECT DISTINCT PRD_LINE
FROM bronze.crm_prd_info;

-- CHECK FOR INVALID DATE ORDERS
   -- END DATE MUST NOT BE EARLIER THAN THE START DATE
   -- END_DATE = START DATE OF THE NEXT RECORD - 1
SELECT * FROM bronze.crm_prd_info
WHERE prd_end_dt < prd_start_dt;

select * from silver.crm_prd_info;
select * from silver.crm_cust_info;