-- INDETIFY OUT-OF-RANGES DATES
SELECT DISTINCT BDATE
FROM bronze.erp_cust_az12
WHERE BDATE < '1910-01-01' OR BDATE > GETDATE();

-- DATA STANDARIZATION & CONSISITENCY
SELECT DISTINCT
GEN
FROM bronze.erp_cust_az12;